DROP TABLE "CLASS";

CREATE TABLE "CLASS" (
	"CLASS_NO"	NUMBER		NOT NULL,
	"PROF_NO"	NUMBER		NOT NULL,
	"CLASS_CODE"	NUMBER		NOT NULL,
	"CLASS_KOR_NAME"	VARCHAR2(100)		NOT NULL,
	"CLASS_ENG_NAME"	VARCHAR2(100)		NULL,
	"CLASS_CATEGORY"	VARCHAR2(1)		NOT NULL,
	"CLASS_YEAR"	VARCHAR2(4)		NOT NULL,
	"CLASS_SEMESTER"	NUMBER		NOT NULL,
	"CLASS_CREDIT"	NUMBER		NOT NULL,
	"CLASS_LOCATION"	VARCHAR2(50)		NULL,
	"CLASS_DAY"	VARCHAR2(3)		NOT NULL,
	"CLASS_TIME"	VARCHAR2(100)		NOT NULL,
	"CLASS_START"	VARCHAR2(100)		NOT NULL,
	"CLASS_DIVISION"	NUMBER		NOT NULL,
	"CLASS_KOR_OUTLINE"	VARCHAR2(3000)		NOT NULL,
	"CLASS_ENG_OUTLINE"	VARCHAR2(3000)		NULL,
	"CLASS_GOAL"	VARCHAR2(1500)		NULL,
	"CLASS_STATUS"	VARCHAR2(1)		NULL,
	"ADMIN_ANSWER"	VARCHAR2(1000)		NULL,
	"CLASS_PHONE"	VARCHAR2(13)		NULL,
	"PROF_LOCATION"	VARCHAR2(50)		NULL,
	"CLASS_PLAN"	VARCHAR2(4000)		NULL,
	"SCORE_ATT"	NUMBER		NOT NULL,
	"SCORE_TASK"	NUMBER		NOT NULL,
	"SCORE_MID"	NUMBER		NOT NULL,
	"SCORE_FIN"	NUMBER		NOT NULL,
	"MAX_STUD"	NUMBER		NOT NULL,
	"CURR_STUD"	NUMBER		NULL
);

COMMENT ON COLUMN "CLASS"."CLASS_NO" IS '강의번호';

COMMENT ON COLUMN "CLASS"."PROF_NO" IS '교수번호';

COMMENT ON COLUMN "CLASS"."CLASS_CODE" IS '과목코드';

COMMENT ON COLUMN "CLASS"."CLASS_KOR_NAME" IS '강의명(국문)';

COMMENT ON COLUMN "CLASS"."CLASS_ENG_NAME" IS '강의명(영문)';

COMMENT ON COLUMN "CLASS"."CLASS_CATEGORY" IS '대면(1)|비대면(2)';

COMMENT ON COLUMN "CLASS"."CLASS_YEAR" IS '년도';

COMMENT ON COLUMN "CLASS"."CLASS_SEMESTER" IS '1학기(1)|2학기(2)';

COMMENT ON COLUMN "CLASS"."CLASS_CREDIT" IS '학점';

COMMENT ON COLUMN "CLASS"."CLASS_LOCATION" IS '강의실';

COMMENT ON COLUMN "CLASS"."CLASS_DAY" IS '강의요일';

COMMENT ON COLUMN "CLASS"."CLASS_TIME" IS '강의시간';

COMMENT ON COLUMN "CLASS"."CLASS_START" IS '강의시작시간';

COMMENT ON COLUMN "CLASS"."CLASS_DIVISION" IS '이수구분 전공필수(1)|전공선택(2)|교양(3)';

COMMENT ON COLUMN "CLASS"."CLASS_KOR_OUTLINE" IS '개요(한글)';

COMMENT ON COLUMN "CLASS"."CLASS_ENG_OUTLINE" IS '개요(영문)';

COMMENT ON COLUMN "CLASS"."CLASS_GOAL" IS '수업목표';

COMMENT ON COLUMN "CLASS"."CLASS_STATUS" IS '승인(Y)|반려(N)';

COMMENT ON COLUMN "CLASS"."ADMIN_ANSWER" IS '관리자답변';

COMMENT ON COLUMN "CLASS"."CLASS_PHONE" IS '관리자연락용도(FK아님)';

COMMENT ON COLUMN "CLASS"."PROF_LOCATION" IS '연구실위치';

COMMENT ON COLUMN "CLASS"."CLASS_PLAN" IS '강의계획';

COMMENT ON COLUMN "CLASS"."SCORE_ATT" IS '출석(%)';

COMMENT ON COLUMN "CLASS"."SCORE_TASK" IS '과제(%)';

COMMENT ON COLUMN "CLASS"."SCORE_MID" IS '중간(%)';

COMMENT ON COLUMN "CLASS"."SCORE_FIN" IS '기말(%)';

COMMENT ON COLUMN "CLASS"."MAX_STUD" IS '최대수강인원';

COMMENT ON COLUMN "CLASS"."CURR_STUD" IS '현재수강인원';

DROP TABLE "CLASSBOARD";

CREATE TABLE "CLASSBOARD" (
	"CLASSBOARD_NO"	NUMBER		NOT NULL,
	"CLASS_NO"	NUMBER		NOT NULL,
	"CLASSBOARD_CATEGORY"	CHAR(1)		NOT NULL,
	"CLASSBOARD_TITLE"	VARCHAR2(1000)		NOT NULL,
	"CLASSBOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CLASSBOARD_ENDDATETIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "CLASSBOARD"."CLASSBOARD_NO" IS '글번호';

COMMENT ON COLUMN "CLASSBOARD"."CLASS_NO" IS '강의번호';

COMMENT ON COLUMN "CLASSBOARD"."CLASSBOARD_CATEGORY" IS '공지사항(CN)|수업자료실(D)|영상자료실(M)';

COMMENT ON COLUMN "CLASSBOARD"."CLASSBOARD_TITLE" IS '제목';

COMMENT ON COLUMN "CLASSBOARD"."CLASSBOARD_CONTENT" IS '내용';

COMMENT ON COLUMN "CLASSBOARD"."CLASSBOARD_ENDDATETIME" IS '최종작성일시';

COMMENT ON COLUMN "CLASSBOARD"."COUNT" IS '조회수';

COMMENT ON COLUMN "CLASSBOARD"."STATUS" IS '게시여부( Y|N)';

DROP TABLE "EVALUATION";

CREATE TABLE "EVALUATION" (
	"EVALUATION_NO"	NUMBER		NOT NULL,
	"CLASS_NO"	NUMBER		NOT NULL,
	"ARTICLE_NO"	NUMBER		NOT NULL,
	"EVALUATION_CATEGORY"	CHAR(1)		NOT NULL,
	"EVALUATION_ANSWER"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "EVALUATION"."EVALUATION_NO" IS '평가번호(SEQ)';

COMMENT ON COLUMN "EVALUATION"."CLASS_NO" IS '강의번호';

COMMENT ON COLUMN "EVALUATION"."ARTICLE_NO" IS '항목번호';

COMMENT ON COLUMN "EVALUATION"."EVALUATION_CATEGORY" IS '객관식(A)|주관식(B)';

COMMENT ON COLUMN "EVALUATION"."EVALUATION_ANSWER" IS '답변';

DROP TABLE "ATTENDANCE";

CREATE TABLE "ATTENDANCE" (
	"ATTENDANCE_NO"	NUMBER		NOT NULL,
	"CLASS_NO"	NUMBER		NOT NULL,
	"STUD_NO"	NUMBER		NOT NULL,
	"ATTENDANCE_DATE"	VARCHAR2(10)		NOT NULL,
	"ATTENDANCE_STATUS"	CHAR(1)		NULL
);

COMMENT ON COLUMN "ATTENDANCE"."ATTENDANCE_NO" IS '출석번호';

COMMENT ON COLUMN "ATTENDANCE"."CLASS_NO" IS '강의번호';

COMMENT ON COLUMN "ATTENDANCE"."STUD_NO" IS '학번';

COMMENT ON COLUMN "ATTENDANCE"."ATTENDANCE_DATE" IS '출석일';

COMMENT ON COLUMN "ATTENDANCE"."ATTENDANCE_STATUS" IS '출석(A)|결석(B)|지각(C)';

DROP TABLE "HOMEWORKP";

CREATE TABLE "HOMEWORKP" (
	"HOMEWORKP_NO"	NUMBER		NOT NULL,
	"CLASS_NO"	NUMBER		NOT NULL,
	"HOMEWORKP_NAME"	VARCHAR2(100)		NOT NULL,
	"HOMEWORKP_CATEGORY"	CHAR(1)		NOT NULL,
	"HOMEWORKP_ENDDATETIME"	VARCHAR2(15)		NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "HOMEWORKP"."HOMEWORKP_NO" IS '과제번호';

COMMENT ON COLUMN "HOMEWORKP"."CLASS_NO" IS '강의번호';

COMMENT ON COLUMN "HOMEWORKP"."HOMEWORKP_NAME" IS '과제명';

COMMENT ON COLUMN "HOMEWORKP"."HOMEWORKP_CATEGORY" IS '제출가능(P)|제출마감(I)';

COMMENT ON COLUMN "HOMEWORKP"."HOMEWORKP_ENDDATETIME" IS '마감일시';

COMMENT ON COLUMN "HOMEWORKP"."STATUS" IS '게시여부(Y|N)';

DROP TABLE "ATTACHMENT";

CREATE TABLE "ATTACHMENT" (
	"ATTACH_NO"	NUMBER		NOT NULL,
	"REF_TYPE"	VARCHAR2(1)		NOT NULL,
	"REF_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(500)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(500)		NULL,
	"PATH"	VARCHAR2(1000)		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "ATTACHMENT"."ATTACH_NO" IS '첨부파일번호';

COMMENT ON COLUMN "ATTACHMENT"."REF_TYPE" IS '메일(M) | 학적변동(A)|( 강의공지사항(CN)|수업자료실(D)|영상자료실(V)) |커뮤니티(B) | 대외활동(C) |공지사항(N) | 강의(CA)|과제목록(P)|제출과제(S)';

COMMENT ON COLUMN "ATTACHMENT"."REF_NO" IS '참조글 번호';

COMMENT ON COLUMN "ATTACHMENT"."ORIGIN_NAME" IS '원본파일명';

COMMENT ON COLUMN "ATTACHMENT"."CHANGE_NAME" IS '수정파일명';

COMMENT ON COLUMN "ATTACHMENT"."PATH" IS '저장폴더경로';

COMMENT ON COLUMN "ATTACHMENT"."STATUS" IS '첨부파일상태(Y|N)';

DROP TABLE "PROFESSOR";

CREATE TABLE "PROFESSOR" (
	"PROF_NO"	NUMBER		NOT NULL,
	"PROF_RANK"	NUMBER		NOT NULL,
	"RANK_CHANGE"	VARCHAR2(10)		NULL,
	"PROF_UNIV"	VARCHAR2(50)		NOT NULL,
	"PROF_DEPARTMENT"	VARCHAR2(50)		NOT NULL,
	"PROF_MAJOR"	VARCHAR2(50)		NOT NULL,
	"PROF_INTO"	VARCHAR2(10)		NOT NULL,
	"PROF_RESIGN"	VARCHAR2(10)		NULL,
	"PROF_LOCATION"	VARCHAR2(50)		NULL,
	"PROF_TEL"	VARCHAR2(13)		NULL,
	"PROF_STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"PROF_APP_DAY"	NUMBER		NULL,
	"PROF_APP_TIME"	NUMBER		NULL
);

COMMENT ON COLUMN "PROFESSOR"."PROF_NO" IS '교수번호';

COMMENT ON COLUMN "PROFESSOR"."PROF_RANK" IS '조교수(1)|부교수(2)|정교수(3)|객원교수(4)';

COMMENT ON COLUMN "PROFESSOR"."PROF_UNIV" IS '소속';

COMMENT ON COLUMN "PROFESSOR"."PROF_DEPARTMENT" IS '학과';

COMMENT ON COLUMN "PROFESSOR"."PROF_MAJOR" IS '전공';

COMMENT ON COLUMN "PROFESSOR"."PROF_STATUS" IS '재직여부 재직(Y)|퇴직(N)';

COMMENT ON COLUMN "PROFESSOR"."PROF_APP_DAY" IS '1(월) || 2(화) || 3(수) || 4(목)|| 5(금)';

COMMENT ON COLUMN "PROFESSOR"."PROF_APP_TIME" IS '1(9시) || 2(10시) || 3(11시) || 4(12시) || 5(1시)..';

DROP TABLE "STUDENT";

CREATE TABLE "STUDENT" (
	"STUD_NO"	NUMBER		NOT NULL,
	"STUD_UNIV"	VARCHAR2(50)		NOT NULL,
	"STUD_DEPARTMENT"	VARCHAR2(50)		NOT NULL,
	"STUD_MAJOR"	VARCHAR2(50)		NOT NULL,
	"STUD_MINOR"	VARCHAR2(50)		NULL,
	"STUD_INTO"	DATE		NOT NULL,
	"STUD_GRAD"	DATE		NULL,
	"STUD_DIVISION"	NUMBER	DEFAULT 1	NOT NULL,
	"STUD_STATUS"	NUMBER	DEFAULT 1	NOT NULL,
	"TOTAL_SEMESTER"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "STUDENT"."STUD_NO" IS '학생번호';

COMMENT ON COLUMN "STUDENT"."STUD_UNIV" IS '대학';

COMMENT ON COLUMN "STUDENT"."STUD_DEPARTMENT" IS '학과';

COMMENT ON COLUMN "STUDENT"."STUD_MAJOR" IS '전공';

COMMENT ON COLUMN "STUDENT"."STUD_MINOR" IS '복수전공';

COMMENT ON COLUMN "STUDENT"."STUD_INTO" IS '입학일자';

COMMENT ON COLUMN "STUDENT"."STUD_GRAD" IS '졸업일자';

COMMENT ON COLUMN "STUDENT"."STUD_DIVISION" IS '입학구분(신입(1)|편입(2)|재입학(3))';

COMMENT ON COLUMN "STUDENT"."STUD_STATUS" IS '학적변동(재학(1)|휴학(2)|졸업(3)|자퇴(4))';

COMMENT ON COLUMN "STUDENT"."TOTAL_SEMESTER" IS '총 이수학기';

DROP TABLE "RESERVED";

CREATE TABLE "RESERVED" (
	"RSVD_NO"	NUMBER		NOT NULL,
	"STUD_NO"	NUMBER		NOT NULL,
	"RSVD_SPACE"	VARCHAR2(2)		NOT NULL,
	"RSVD_NUM"	NUMBER	DEFAULT 1	NOT NULL,
	"RSVD_DATE"	VARCHAR2(20)		NOT NULL,
	"RSVD_START"	VARCHAR2(20)		NOT NULL,
	"RSVD_END"	VARCHAR2(20)		NULL,
	"RSVD_STATUS"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESERVED"."RSVD_SPACE" IS '좌석(S)|스터디룸(R) A|B|C|D';

COMMENT ON COLUMN "RESERVED"."RSVD_STATUS" IS '사용중|사용완료|차단';

DROP TABLE "SPAM";

CREATE TABLE "SPAM" (
	"SPAM_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"SUSER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SPAM"."SPAM_NO" IS '스팸번호';

COMMENT ON COLUMN "SPAM"."USER_NO" IS '학번||교수번호';

COMMENT ON COLUMN "SPAM"."SUSER_NO" IS '학번||교수번호';

DROP TABLE "CONTACT";

CREATE TABLE "CONTACT" (
	"CONTACT_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"NAME"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NULL,
	"PHONE"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "CONTACT"."CONTACT_NO" IS '주소록번호';

COMMENT ON COLUMN "CONTACT"."USER_NO" IS '학번||교수번호';

COMMENT ON COLUMN "CONTACT"."NAME" IS '이름';

COMMENT ON COLUMN "CONTACT"."EMAIL" IS '이메일';

COMMENT ON COLUMN "CONTACT"."PHONE" IS '연락 처';

DROP TABLE "APPOINTMENT";

CREATE TABLE "APPOINTMENT" (
	"APP_NO"	NUMBER		NOT NULL,
	"STUD_NO"	NUMBER		NOT NULL,
	"PROF_NO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(60)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"APP_DATE"	VARCHAR2(50)		NOT NULL,
	"APP_STATUS"	NUMBER	DEFAULT 1	NOT NULL,
	"REASON"	VARCHAR2(100)		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "APPOINTMENT"."APP_NO" IS '상담신청 번호';

COMMENT ON COLUMN "APPOINTMENT"."STUD_NO" IS '학생번호';

COMMENT ON COLUMN "APPOINTMENT"."PROF_NO" IS '교수번호';

COMMENT ON COLUMN "APPOINTMENT"."TITLE" IS '제목';

COMMENT ON COLUMN "APPOINTMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "APPOINTMENT"."ENROLL_DATE" IS '신청날짜';

COMMENT ON COLUMN "APPOINTMENT"."APP_DATE" IS '상담일시';

COMMENT ON COLUMN "APPOINTMENT"."APP_STATUS" IS '1 대기 ||  2 승인 || 3 완료 || 4 반려';

COMMENT ON COLUMN "APPOINTMENT"."REASON" IS '반려사유';

COMMENT ON COLUMN "APPOINTMENT"."STATUS" IS '상태';

DROP TABLE "MESSAGE";

CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"MSG_WRITER"	VARCHAR2(100)		NOT NULL,
	"MSG_READER"	VARCHAR2(100)		NOT NULL,
	"MSG_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"READYN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"DELETEYN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"IMP_MSG"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"SEND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"READ_DATE"	DATE		NULL,
	"MSG_ALERT"	VARCHAR2(1)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS 'PK';

COMMENT ON COLUMN "MESSAGE"."MSG_WRITER" IS '학생/교수 참조 FK';

COMMENT ON COLUMN "MESSAGE"."MSG_READER" IS '학생/교수 참조 FK';

COMMENT ON COLUMN "MESSAGE"."MSG_CONTENT" IS '쪽지내용';

COMMENT ON COLUMN "MESSAGE"."READYN" IS '읽기상태(Y/N)';

COMMENT ON COLUMN "MESSAGE"."DELETEYN" IS '삭제여부(Y/N)';

COMMENT ON COLUMN "MESSAGE"."IMP_MSG" IS '중요(Y/N)';

COMMENT ON COLUMN "MESSAGE"."SEND_DATE" IS '보낸 날짜';

COMMENT ON COLUMN "MESSAGE"."READ_DATE" IS '읽은날짜를 추가';

COMMENT ON COLUMN "MESSAGE"."MSG_ALERT" IS ''Y'면 노출/ 'N'이면 비노출';

DROP TABLE "EVENT";

CREATE TABLE "EVENT" (
	"EVENT_NO"	NUMBER		NOT NULL,
	"EVENT_USER"	NUMBER		NOT NULL,
	"EVENT_TITLE"	VARCHAR2(100)		NOT NULL,
	"EVENT_CONTENT"	VARCHAR2(1000)		NULL,
	"START_DATE"	VARCHAR2(40)		NULL,
	"END_DATE"	VARCHAR2(40)		NULL,
	"ALLDAY_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"DELETE_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "EVENT"."EVENT_NO" IS 'PK';

COMMENT ON COLUMN "EVENT"."EVENT_USER" IS '학생 교수번호 참조';

COMMENT ON COLUMN "EVENT"."EVENT_CONTENT" IS '메모';

COMMENT ON COLUMN "EVENT"."START_DATE" IS '시간까지 받기';

COMMENT ON COLUMN "EVENT"."END_DATE" IS '시간까지 받기';

COMMENT ON COLUMN "EVENT"."ALLDAY_YN" IS 'Y/N';

COMMENT ON COLUMN "EVENT"."DELETE_YN" IS '삭제유무 Y/N';

DROP TABLE "CERTIFICATE";

CREATE TABLE "CERTIFICATE" (
	"CER_NO"	NUMBER		NOT NULL,
	"STUD_NO"	NUMBER		NOT NULL,
	"CER_TYPE"	NUMBER		NOT NULL,
	"USEFOR"	VARCHAR2(20)		NOT NULL,
	"TO_TYPE"	NUMBER		NOT NULL,
	"T0_WHOM"	VARCHAR2(20)		NOT NULL,
	"PAID"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "CERTIFICATE"."CER_NO" IS '증명서발급번호';

COMMENT ON COLUMN "CERTIFICATE"."STUD_NO" IS '학생번호';

COMMENT ON COLUMN "CERTIFICATE"."CER_TYPE" IS '1 (국)졸업증명서 || 2 (영) 졸업증명서 || 3 (국) 재적증명서 || 4 (영) 재적증명서 || 5 (국) 성적증명서 || 6 (영) 성적증명서';

COMMENT ON COLUMN "CERTIFICATE"."USEFOR" IS '용도';

COMMENT ON COLUMN "CERTIFICATE"."TO_TYPE" IS '1기업||2기관||3기타';

COMMENT ON COLUMN "CERTIFICATE"."T0_WHOM" IS '제출처명';

COMMENT ON COLUMN "CERTIFICATE"."PAID" IS 'Y||N';

COMMENT ON COLUMN "CERTIFICATE"."STATUS" IS 'Y||N';

DROP TABLE "ACADEMIC_STATUS";

CREATE TABLE "ACADEMIC_STATUS" (
	"AS_NO"	NUMBER		NOT NULL,
	"STUD_NO"	NUMBER		NOT NULL,
	"AS_TYPE"	NUMBER		NOT NULL,
	"AS_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OFF_TYPE"	NUMBER		NULL,
	"REASON"	NUMBER		NULL,
	"REASON_DETAIL"	VARCHAR2(300)		NULL,
	"OFF_YEAR"	NUMBER		NULL,
	"OFF_SEMESTER"	NUMBER		NULL,
	"OFFUNTIL_YEAR"	NUMBER		NULL,
	"OFFUNTIL_SEMESTER"	NUMBER		NULL,
	"BACK_YEAR"	NUMBER		NULL,
	"BACK_SEMESTER"	NUMBER		NULL,
	"PROGRESS"	NUMBER	DEFAULT 0	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "ACADEMIC_STATUS"."AS_NO" IS '학적변동번호';

COMMENT ON COLUMN "ACADEMIC_STATUS"."STUD_NO" IS '학생번호';

COMMENT ON COLUMN "ACADEMIC_STATUS"."AS_TYPE" IS '1 휴학  |  2 복학';

COMMENT ON COLUMN "ACADEMIC_STATUS"."AS_DATE" IS '신청일자';

COMMENT ON COLUMN "ACADEMIC_STATUS"."OFF_TYPE" IS '1 일반휴학 || 2 군입대휴학 || 3 임신/출산휴학 || 4 육아휴학';

COMMENT ON COLUMN "ACADEMIC_STATUS"."REASON" IS '1 개인사정 || 2 군입대 || 3 기타';

COMMENT ON COLUMN "ACADEMIC_STATUS"."REASON_DETAIL" IS '휴학사유 상세';

COMMENT ON COLUMN "ACADEMIC_STATUS"."OFF_YEAR" IS '신청년도';

COMMENT ON COLUMN "ACADEMIC_STATUS"."OFF_SEMESTER" IS '1 || 2';

COMMENT ON COLUMN "ACADEMIC_STATUS"."OFFUNTIL_YEAR" IS '복학희망년도';

COMMENT ON COLUMN "ACADEMIC_STATUS"."OFFUNTIL_SEMESTER" IS '1 || 2';

COMMENT ON COLUMN "ACADEMIC_STATUS"."BACK_YEAR" IS '복학신청년도';

COMMENT ON COLUMN "ACADEMIC_STATUS"."BACK_SEMESTER" IS '1 || 2';

COMMENT ON COLUMN "ACADEMIC_STATUS"."PROGRESS" IS '1 담당교수승인|2 학사지원과승인|3 최종승인';

COMMENT ON COLUMN "ACADEMIC_STATUS"."STATUS" IS '상태';

DROP TABLE "HOMEWORKS";

CREATE TABLE "HOMEWORKS" (
	"HOMEWORKS_NO"	NUMBER		NOT NULL,
	"HOMEWORKP_NO"	NUMBER		NOT NULL,
	"STUD_NO"	NUMBER		NOT NULL,
	"GRADE_STATUS"	CHAR(1)		NOT NULL,
	"SCORE"	NUMBER		NULL,
	"FEEDBACK"	VARCHAR2(4000)		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "HOMEWORKS"."HOMEWORKS_NO" IS '과제번호';

COMMENT ON COLUMN "HOMEWORKS"."HOMEWORKP_NO" IS '참조게시글번호';

COMMENT ON COLUMN "HOMEWORKS"."STUD_NO" IS '학번';

COMMENT ON COLUMN "HOMEWORKS"."GRADE_STATUS" IS '채점(A)|미채점(B)';

COMMENT ON COLUMN "HOMEWORKS"."SCORE" IS '점수';

COMMENT ON COLUMN "HOMEWORKS"."FEEDBACK" IS '피드백';

COMMENT ON COLUMN "HOMEWORKS"."STATUS" IS '게시여부(Y|N)';

DROP TABLE "ACADEMIC_CALENDAR";

CREATE TABLE "ACADEMIC_CALENDAR" (
	"CAL_NO"	NUMBER		NOT NULL,
	"CAL_NAME"	VARCHAR2(100)		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
	"YEAR"	NUMBER		NOT NULL,
	"MONTH"	NUMBER		NOT NULL,
	"DAY"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."CAL_NO" IS '학사일정 번호';

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."CAL_NAME" IS '학사일정';

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."START_DATE" IS '시작일';

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."END_DATE" IS '종료일';

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."YEAR" IS '년도';

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."MONTH" IS '월';

COMMENT ON COLUMN "ACADEMIC_CALENDAR"."DAY" IS '07(금) | 08(토)~09(일)';

DROP TABLE "REPLY";

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(400)		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS 'PK';

COMMENT ON COLUMN "REPLY"."USER_NO" IS '학번 FK';

COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '번호 PK';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "REPLY"."CREATE_DATE" IS '댓글작성날짜';

COMMENT ON COLUMN "REPLY"."STATUS" IS '댓글상태(Y/N)';

DROP TABLE "TODO";

CREATE TABLE "TODO" (
	"TODO_NO"	NUMBER		NOT NULL,
	"TODO_USER"	NUMBER		NOT NULL,
	"TODO_CONTENT"	VARCHAR2(150)		NOT NULL,
	"TODO_DEL"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"TODO_DATE"	VARCHAR2(20)	DEFAULT SYSDATE	NOT NULL,
	"TODO_CHECK"	CHAR(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "TODO"."TODO_NO" IS 'PK';

COMMENT ON COLUMN "TODO"."TODO_USER" IS '학생 교수번호 참조';

COMMENT ON COLUMN "TODO"."TODO_CONTENT" IS 'TODOLIST 내용';

COMMENT ON COLUMN "TODO"."TODO_DEL" IS 'TODO 삭제여부 (Y/N)';

COMMENT ON COLUMN "TODO"."TODO_DATE" IS '생성날짜';

COMMENT ON COLUMN "TODO"."TODO_CHECK" IS '체크유무(Y/N)';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"USER)DIVISION"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_YN"	VARCHAR2(1)		NULL,
	"DELETE"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"BO_CATEGORY"	NUMBER		NOT NULL,
	"SUB_CATEGORY"	NUMBER		NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '번호 PK';

COMMENT ON COLUMN "BOARD"."USER_NO" IS '작성자 번호 FK';

COMMENT ON COLUMN "BOARD"."USER)DIVISION" IS '1 학생/2 교수/3 관리자';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '내용';

COMMENT ON COLUMN "BOARD"."COUNT" IS 'DEFAULT 0';

COMMENT ON COLUMN "BOARD"."CREATE_DATE" IS '작성일';

COMMENT ON COLUMN "BOARD"."NOTICE_YN" IS '공지여부(Y/N) , 체크시 상단';

COMMENT ON COLUMN "BOARD"."DELETE" IS '삭제여부(Y/N)';

COMMENT ON COLUMN "BOARD"."BO_CATEGORY" IS '1 공지 2 대외 3 공모전 4 커뮤니티';

COMMENT ON COLUMN "BOARD"."SUB_CATEGORY" IS '5자유 6 취업 7정보공유';

DROP TABLE "SEMESTER";

CREATE TABLE "SEMESTER" (
	"SEM_NO"	NUMBER		NOT NULL,
	"Key"	VARCHAR(255)		NOT NULL,
	"SEM_YEAR"	DATE	DEFAULT SYSDATE	NOT NULL,
	"SEM_SEMETER"	NUMBER		NOT NULL,
	"SEM_CREDIT"	NUMBER		NULL,
	"SME_STATUS"	CHAR(1)		NULL
);

COMMENT ON COLUMN "SEMESTER"."SEM_NO" IS '이수학기 번호';

COMMENT ON COLUMN "SEMESTER"."SEM_YEAR" IS '수강년도';

COMMENT ON COLUMN "SEMESTER"."SEM_SEMETER" IS '이수학기';

COMMENT ON COLUMN "SEMESTER"."SEM_CREDIT" IS '이수학점';

COMMENT ON COLUMN "SEMESTER"."SME_STATUS" IS '이수상태 이수(Y)|미이수(N)';

DROP TABLE "MAIL_FROM";

CREATE TABLE "MAIL_FROM" (
	"MAIL_FROM_NO"	NUMBER		NOT NULL,
	"FROM"	NUMBER		NOT NULL,
	"FROM_ADD"	VARCHAR2(100)		NOT NULL,
	"TITLE"	VARCHAR2(60)		NULL,
	"CONTENT"	CLOB		NULL,
	"SEND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TO_ME"	VARCHAR2(1)	DEFAULT N	NULL,
	"SAVE_STATUS"	VARCHAR2(1)	DEFAULT N	NULL
);

COMMENT ON COLUMN "MAIL_FROM"."MAIL_FROM_NO" IS '발신메일번호';

COMMENT ON COLUMN "MAIL_FROM"."FROM" IS '학번||교번';

COMMENT ON COLUMN "MAIL_FROM"."FROM_ADD" IS '학번||교번 @~~';

COMMENT ON COLUMN "MAIL_FROM"."TITLE" IS '제목';

COMMENT ON COLUMN "MAIL_FROM"."CONTENT" IS '내용';

COMMENT ON COLUMN "MAIL_FROM"."SEND_DATE" IS '보낸일시';

COMMENT ON COLUMN "MAIL_FROM"."TO_ME" IS 'N || Y';

COMMENT ON COLUMN "MAIL_FROM"."SAVE_STATUS" IS 'N || Y';

DROP TABLE "MAIL_TO";

CREATE TABLE "MAIL_TO" (
	"MAIL_TO_NO"	NUMBER		NOT NULL,
	"MAIL_FROM_NO"	NUMBER		NOT NULL,
	"TO"	NUMBER		NOT NULL,
	"TO_ADD"	VARCHAR2(100)		NOT NULL,
	"IMPORTANT"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"READ_DATE"	DATE		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"SPAM_STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CC_STATUS"	VARCHAR2(1)	DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "MAIL_TO"."MAIL_TO_NO" IS '수신메일번호';

COMMENT ON COLUMN "MAIL_TO"."MAIL_FROM_NO" IS '발신메일번호';

COMMENT ON COLUMN "MAIL_TO"."TO" IS '학번||교번';

COMMENT ON COLUMN "MAIL_TO"."TO_ADD" IS '학번@~~||교번@~~';

COMMENT ON COLUMN "MAIL_TO"."IMPORTANT" IS 'Y||N';

COMMENT ON COLUMN "MAIL_TO"."READ_DATE" IS '읽은시간';

COMMENT ON COLUMN "MAIL_TO"."STATUS" IS 'Y||N  (휴지통)';

COMMENT ON COLUMN "MAIL_TO"."SPAM_STATUS" IS 'Y||N';

COMMENT ON COLUMN "MAIL_TO"."CC_STATUS" IS 'Y || N';

DROP TABLE "CLASS_STUD";

CREATE TABLE "CLASS_STUD" (
	"CLASS_STUD_NO"	NUMBER		NOT NULL,
	"CLASS_NO"	NUMBER		NOT NULL,
	"STUD_NO"	NUMBER		NOT NULL,
	"STATUS"	VARCHAR2(1)		NULL
);

COMMENT ON COLUMN "CLASS_STUD"."CLASS_STUD_NO" IS '수강학생번호';

COMMENT ON COLUMN "CLASS_STUD"."CLASS_NO" IS '강의번호';

COMMENT ON COLUMN "CLASS_STUD"."STUD_NO" IS '학번';

COMMENT ON COLUMN "CLASS_STUD"."STATUS" IS '수강중(Y)|수강완료(N)';

DROP TABLE "GRADE";

CREATE TABLE "GRADE" (
	"GRADE_NO"	NUMBER		NOT NULL,
	"CLASS_STUD_NO"	NUMBER		NOT NULL,
	"STUD_GRADE"	NUMBER		NOT NULL,
	"ATTENDANCE"	NUMBER		NULL,
	"ASSIGNMENTS"	NUMBER		NULL,
	"MID"	NUMBER		NULL,
	"FINAL"	NUMBER		NULL,
	"SCORE"	NUMBER		NULL,
	"GRADE"	VARCHAR2(5)		NULL
);

COMMENT ON COLUMN "GRADE"."GRADE_NO" IS '성적 번호';

COMMENT ON COLUMN "GRADE"."CLASS_STUD_NO" IS '수강학생번호';

COMMENT ON COLUMN "GRADE"."STUD_GRADE" IS '학년';

COMMENT ON COLUMN "GRADE"."ATTENDANCE" IS '출석';

COMMENT ON COLUMN "GRADE"."ASSIGNMENTS" IS '과제';

COMMENT ON COLUMN "GRADE"."MID" IS '중간고사';

COMMENT ON COLUMN "GRADE"."FINAL" IS '기말고사';

COMMENT ON COLUMN "GRADE"."SCORE" IS '총 점수';

COMMENT ON COLUMN "GRADE"."GRADE" IS 'A, B, C, B+ ...';

DROP TABLE "USER";

CREATE TABLE "USER" (
	"USER_NO"	NUMBER		NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"KOR_NAME"	VARCHAR2(30)		NOT NULL,
	"ENG_NAME"	VARCHAR2(30)		NULL,
	"BIRTHDAY"	VARCHAR2(10)		NOT NULL,
	"GENDER"	VARCHAR2(1)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"PHONE"	VARCHAR2(13)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NOT NULL,
	"NATION"	VARCHAR2(50)	DEFAULT '대한민국'	NOT NULL,
	"WEBMAIL"	VARCHAR2(50)		NULL,
	"USER_DIV"	NUMBER		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "USER"."USER_NO" IS '학번 또는 교번';

COMMENT ON COLUMN "USER"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "USER"."KOR_NAME" IS '성명(한글)';

COMMENT ON COLUMN "USER"."ENG_NAME" IS '성명(영문)';

COMMENT ON COLUMN "USER"."BIRTHDAY" IS '생년월일';

COMMENT ON COLUMN "USER"."GENDER" IS '성별 여성(F)|남성(M)';

COMMENT ON COLUMN "USER"."EMAIL" IS '이메일';

COMMENT ON COLUMN "USER"."PHONE" IS '연락처';

COMMENT ON COLUMN "USER"."ADDRESS" IS '주소';

COMMENT ON COLUMN "USER"."NATION" IS '국적';

COMMENT ON COLUMN "USER"."WEBMAIL" IS '웹메일주소';

COMMENT ON COLUMN "USER"."USER_DIV" IS '학생(1)/교수(2)/관리자(3)';

COMMENT ON COLUMN "USER"."PROFILE_IMG" IS '프로필이미지경로/수정파일명';

ALTER TABLE "CLASS" ADD CONSTRAINT "PK_CLASS" PRIMARY KEY (
	"CLASS_NO"
);

ALTER TABLE "CLASSBOARD" ADD CONSTRAINT "PK_CLASSBOARD" PRIMARY KEY (
	"CLASSBOARD_NO"
);

ALTER TABLE "EVALUATION" ADD CONSTRAINT "PK_EVALUATION" PRIMARY KEY (
	"EVALUATION_NO"
);

ALTER TABLE "ATTENDANCE" ADD CONSTRAINT "PK_ATTENDANCE" PRIMARY KEY (
	"ATTENDANCE_NO"
);

ALTER TABLE "HOMEWORKP" ADD CONSTRAINT "PK_HOMEWORKP" PRIMARY KEY (
	"HOMEWORKP_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"ATTACH_NO"
);

ALTER TABLE "PROFESSOR" ADD CONSTRAINT "PK_PROFESSOR" PRIMARY KEY (
	"PROF_NO"
);

ALTER TABLE "STUDENT" ADD CONSTRAINT "PK_STUDENT" PRIMARY KEY (
	"STUD_NO"
);

ALTER TABLE "RESERVED" ADD CONSTRAINT "PK_RESERVED" PRIMARY KEY (
	"RSVD_NO"
);

ALTER TABLE "SPAM" ADD CONSTRAINT "PK_SPAM" PRIMARY KEY (
	"SPAM_NO"
);

ALTER TABLE "CONTACT" ADD CONSTRAINT "PK_CONTACT" PRIMARY KEY (
	"CONTACT_NO"
);

ALTER TABLE "APPOINTMENT" ADD CONSTRAINT "PK_APPOINTMENT" PRIMARY KEY (
	"APP_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVENT_NO"
);

ALTER TABLE "CERTIFICATE" ADD CONSTRAINT "PK_CERTIFICATE" PRIMARY KEY (
	"CER_NO"
);

ALTER TABLE "ACADEMIC_STATUS" ADD CONSTRAINT "PK_ACADEMIC_STATUS" PRIMARY KEY (
	"AS_NO"
);

ALTER TABLE "HOMEWORKS" ADD CONSTRAINT "PK_HOMEWORKS" PRIMARY KEY (
	"HOMEWORKS_NO"
);

ALTER TABLE "ACADEMIC_CALENDAR" ADD CONSTRAINT "PK_ACADEMIC_CALENDAR" PRIMARY KEY (
	"CAL_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "TODO" ADD CONSTRAINT "PK_TODO" PRIMARY KEY (
	"TODO_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "SEMESTER" ADD CONSTRAINT "PK_SEMESTER" PRIMARY KEY (
	"SEM_NO"
);

ALTER TABLE "MAIL_FROM" ADD CONSTRAINT "PK_MAIL_FROM" PRIMARY KEY (
	"MAIL_FROM_NO"
);

ALTER TABLE "MAIL_TO" ADD CONSTRAINT "PK_MAIL_TO" PRIMARY KEY (
	"MAIL_TO_NO"
);

ALTER TABLE "CLASS_STUD" ADD CONSTRAINT "PK_CLASS_STUD" PRIMARY KEY (
	"CLASS_STUD_NO"
);

ALTER TABLE "GRADE" ADD CONSTRAINT "PK_GRADE" PRIMARY KEY (
	"GRADE_NO"
);

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "CLASS" ADD CONSTRAINT "FK_PROFESSOR_TO_CLASS_1" FOREIGN KEY (
	"PROF_NO"
)
REFERENCES "PROFESSOR" (
	"PROF_NO"
);

ALTER TABLE "CLASSBOARD" ADD CONSTRAINT "FK_CLASS_TO_CLASSBOARD_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "CLASS" (
	"CLASS_NO"
);

ALTER TABLE "EVALUATION" ADD CONSTRAINT "FK_CLASS_TO_EVALUATION_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "CLASS" (
	"CLASS_NO"
);

ALTER TABLE "ATTENDANCE" ADD CONSTRAINT "FK_CLASS_TO_ATTENDANCE_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "CLASS" (
	"CLASS_NO"
);

ALTER TABLE "ATTENDANCE" ADD CONSTRAINT "FK_STUDENT_TO_ATTENDANCE_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "HOMEWORKP" ADD CONSTRAINT "FK_CLASS_TO_HOMEWORKP_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "CLASS" (
	"CLASS_NO"
);

ALTER TABLE "PROFESSOR" ADD CONSTRAINT "FK_USER_TO_PROFESSOR_1" FOREIGN KEY (
	"PROF_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "STUDENT" ADD CONSTRAINT "FK_USER_TO_STUDENT_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "RESERVED" ADD CONSTRAINT "FK_STUDENT_TO_RESERVED_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "APPOINTMENT" ADD CONSTRAINT "FK_STUDENT_TO_APPOINTMENT_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "APPOINTMENT" ADD CONSTRAINT "FK_PROFESSOR_TO_APPOINTMENT_1" FOREIGN KEY (
	"PROF_NO"
)
REFERENCES "PROFESSOR" (
	"PROF_NO"
);

ALTER TABLE "CERTIFICATE" ADD CONSTRAINT "FK_STUDENT_TO_CERTIFICATE_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "ACADEMIC_STATUS" ADD CONSTRAINT "FK_STUDENT_TO_ACADEMIC_STATUS_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "HOMEWORKS" ADD CONSTRAINT "FK_HOMEWORKP_TO_HOMEWORKS_1" FOREIGN KEY (
	"HOMEWORKP_NO"
)
REFERENCES "HOMEWORKP" (
	"HOMEWORKP_NO"
);

ALTER TABLE "HOMEWORKS" ADD CONSTRAINT "FK_STUDENT_TO_HOMEWORKS_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_USER_TO_REPLY_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_TO_REPLY_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_USER_TO_BOARD_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "SEMESTER" ADD CONSTRAINT "FK_STUDENT_TO_SEMESTER_1" FOREIGN KEY (
	"Key"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "MAIL_FROM" ADD CONSTRAINT "FK_USER_TO_MAIL_FROM_1" FOREIGN KEY (
	"FROM"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "MAIL_TO" ADD CONSTRAINT "FK_MAIL_FROM_TO_MAIL_TO_1" FOREIGN KEY (
	"MAIL_FROM_NO"
)
REFERENCES "MAIL_FROM" (
	"MAIL_FROM_NO"
);

ALTER TABLE "MAIL_TO" ADD CONSTRAINT "FK_USER_TO_MAIL_TO_1" FOREIGN KEY (
	"TO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "CLASS_STUD" ADD CONSTRAINT "FK_CLASS_TO_CLASS_STUD_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "CLASS" (
	"CLASS_NO"
);

ALTER TABLE "CLASS_STUD" ADD CONSTRAINT "FK_STUDENT_TO_CLASS_STUD_1" FOREIGN KEY (
	"STUD_NO"
)
REFERENCES "STUDENT" (
	"STUD_NO"
);

ALTER TABLE "GRADE" ADD CONSTRAINT "FK_CLASS_STUD_TO_GRADE_1" FOREIGN KEY (
	"CLASS_STUD_NO"
)
REFERENCES "CLASS_STUD" (
	"CLASS_STUD_NO"
);

